#!/bin/sh
deluser --remove-home [name]

# This will delete a real user and the user's home directory. 
#
# If you had previously configured sudo privileges for the user you deleted
#  by editing the /etc/sudoers file, you should remove the relevant line in
#  the file by typing: visudo.
